### PR TITLE
[Changed] WoWAds renamed to WoWMua

### LINKED ISSUE #21: git submodule some of the things
ala LibQTip.

### PR DESCRIPTION
**Pull request by JanGalek**

### CODE REVIEW

**Comment by idiomatic** [comment]
Please `git pull` before `git commit` so we have fewer conflicts.

**Comment by idiomatic** [comment]
@JanGalek, can you merge idiomatic:master to wowmua:master?

**Comment by JanGalek** [comment]
@JanGalek yes, sorry :)

**Comment by JanGalek** [comment]
I did rebase ;)

**Pull request merged**
