### PR TITLE
[Changed] Changelog format

### PR DESCRIPTION
**Pull request by JanGalek**
based on https://keepachangelog.com/en/1.0.0/

### CODE REVIEW

**Comment by idiomatic** [comment]
change CHANGELOG assignment in Makefile too.

**Comment by idiomatic** [comment]
and I'd advise using Added instead of Fixed for initial language translations.

**Comment by JanGalek** [comment]
There is Added too ;)

**Comment by JanGalek** [comment]
There is problem with ```git submodule update --remote --merge```

**Comment by JanGalek** [comment]
Tried on local and there is no problem, I see there is new release for libqtip 9.0.1.2 which should resolve it.

**Comment by idiomatic** [comment]
I have to say I'm impressed that you read and partially understood old changelog entries.  Well done.

**Comment by idiomatic** [comment]
This event is a :-1: for submodules and our Makefile-magic updating.

**Pull request merged**
