### PR TITLE
Moved: Libs to submodule

### LINKED ISSUE #21: git submodule some of the things
ala LibQTip.

### PR DESCRIPTION
**Pull request by JanGalek**
Moved to submodule:
- LibStub
- Ace3

Resolved: https://github.com/idiomatic/HandyNotes_Achievements/issues/21

### CODE REVIEW

**Comment by idiomatic** [comment]
i cannot say whether @wowace-clone is reputable.

**Comment by JanGalek** [comment]
You're right with https://github.com/wowace-clone/Ace3 is not actual. so I'm cloning and converting it to git, and I try make automate update :)

**Comment by idiomatic** [comment]
It could be simplest just to revert #23, and leave these Subversion-originated libs embedded.  Ace3 and LibStub are very static. Also, embedding would need no automated `git submodule update`.

**Comment by JanGalek** [comment]
Yes, maybe we can cancel dependencie on this libraries (future), I'll do better investigation.

**Comment by idiomatic** [comment]
> Yes, maybe we can cancel dependency on this libraries (future)

I'm in conflict here.  My normal instinct is to embed, internalize, inline, and remove external dependencies (driven by surprise avoidance, and minimizing API impedance).  It's the philosophy behind my merging many microservices in a job in 2016, where the implementation language resulted in excess of 40% code-noise and negative operational benefit.

However, I submit there is some value in leveraging mainstream convention, especially if the library is "light touch", "low learning curve", "less opinionated", and does not result in excessive "boilerplate". 

In my opinion, Ace3 is more useful than an impediment, especially for publicly published, collaboratively maintained, more polished add-ons.  Conversely, I've omitted Ace3 for some private hack add-ons where the benefit of reinventing that which Ace3 provides is a valuable lesson.

Conclusion: dependencies are situational.

**Pull request merged**
